app:
  name: "bluebell"
  mode: "dev"
  port: 9090

auth:
  jwt_expire: 8760

log:
  level: "debug"
  filename: "bluebell.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 13306
  user: "root"
  password: "123456"
  db: "bluebell"
  max_open_connection: 20
  max_idle_connection: 10

redis:
  host: "127.0.0.1"
  port: 16379
  password: ""
  db: 0
  pool_size: 100

snowflake:
  start_time: "2020-07-01"
  machine_id: 1

encrypt:
  secret_key: "StudentCWZ"

gin:
  mode: "debug"